# Outline of Brookyln College guidelines:

In brief, there are two important obligations: to inform students that they need to be aware of the CUNY Academic Integrity policy, and to report suspected violations. These two obligations are described more fully below:

## Syllabus Requirements

According to the Brooklyn College "Fall 2016 Obligations of the Faculty and Syllabus Preparation" document, all syllabi must include the following statement concerning Academic Integrity:

"The faculty and administration of Brooklyn College support an environment free from cheating and plagiarism. Each student is responsible for being aware of what constitutes cheating and plagiarism and for avoiding both. The complete text of the CUNY Academic Integrity Policy and the Brooklyn College procedure for policy implementation can be found at www.brooklyn.cuny.edu/bc/policies. If a faculty member suspects a violation of academic integrity and, upon investigation, confirms that violation, or if the student admits the violation, the faculty member must report the violation."

##Reporting Requirements

When a suspected violation is confirmed through investigation, or if the student admits the violation, then faculty must report the violation. The reporting process currently involves filing the FAR report (Faculty Action Report for Incidents of Academic Dishonesty.) with the College’s Academic Integrity Officer, Mr. Patrick Kavanagh (Office of the Associate Provost for Academic Programs: 3208 Boylan Hall, 718-951-5771). 

Patrick’s email is: kavanagh@brooklyn.cuny.edu

The language in the FAR report suggests a broader obligation to file this report whenever "a faculty member finds compelling evidence that a suspected violation of the CUNY policy on Academic Integrity has occurred".

## Reporting a suspected violation (FAR REPORT)

If you have questions about the process, Patrick is very helpful and knowledgeable and can guide you through the details. The FAR report is mostly self-explanatory and involves three sections

### Section A: Information about the student

- fill out basic information about student name, CUNYFirst ID, email, date of incident etc.
  a. You are given space to "describe the incident". You can attach an additional document if necessary
  b. You are required to "Indicate the outcome of your discussion of the violation with the student". So, it is necessary to schedule a time to meet with or speak with this student.
  c. Section A notes that: "Evidence must accompany allegations. For plagiarism, please attach the syllabus and the assignment sheet in addition to the documentation of plagiarism, such as the Safe Assign Report or copy of the paper with portions found to be plagiarized highlighted along with the original source."

### Section B: Academic (Grade) Sanction

- given the option to recommend 1) failing grade on Exam/Assignment, 2) Failing grade for Course, or Other (please explain)
- required to report whether the student accepts the sanction

### Section C: Disciplinary Complaint Option
	
- speak to Patrick about this one.

## Helpful links:

[http://libguides.brooklyn.cuny.edu/plagiarism](http://libguides.brooklyn.cuny.edu/plagiarism)


##List of websites that students may use for cheating:

Most of these websites offer a similar set of services. 

- [https://www.studyblue.com](https://www.studyblue.com)
- [https://www.coursehero.com](https://www.coursehero.com)
- [https://www.chegg.com](https://www.chegg.com)
- [https://studentshare.net](https://studentshare.net)
- Brooklyn College Facebook in the know (a facebook group)
- [https://www.slader.com](https://www.slader.com)

There are many more similar kinds of sites
