# Websites and cheating

Students are sharing exams, assignments, old papers, homework questions, etc. across numerous online platforms. 

- [https://www.studyblue.com](https://www.studyblue.com)
- [https://www.coursehero.com](https://www.coursehero.com)
- [https://www.chegg.com](https://www.chegg.com)
- [https://studentshare.net](https://studentshare.net)
- Brooklyn College Facebook in the know (a facebook group)
- [https://www.slader.com](https://www.slader.com)

## Exam/Assignment Repositories

These sites offer large repositories of test banks, assignments, homework questions, papers, essays, answers etc., that can be downloaded for free, or for the cost of a membership. All of the materials have been uploaded by other students. You may be surprised to see most of if not all of your own assignments/exams etc. uploaded to these websites.

If you find your materials on one of these websites, and do not want your material there, then you may be able to contact have the material removed by making a takedown request.

## "Tutoring" / paying somebody 

Most of theses sites offer personal tutoring services. For a fee, a student subscriber can post a question to the tutoring service, and then pay someone to "help" them with the question. 

Many students use this to pay someone else to do their work for them, and then they cheat by handing in the tutor's work as their own. Remarkably, many of these sites make the results of tutoring requests searchable. So, for example, if you had an account with the service, you could search your own assignment questions to determine whether a tutor has completed one of them. Then you could cross-reference the tutor generated work with the work submitted by your students.

## Are your materials online?

Find out easily by googling your portions of your materials. You can also find yourself as an instructor on many of these sites, and then find materials that students have uploaded and associated specifically with your course.



